package io.zeebe.client.api.commands;

import io.zeebe.client.api.ZeebeFuture;

public interface FinalCommandStep<T>
{

    /**
     * Sends the command to the Zeebe broker. This operation is asynchronous.
     * In case of success, the future returns the event that was generated by the
     * Zeebe broker in response to the command.
     *
     * <p>
     * Call {@link ZeebeFuture#join()} to wait until the response is available.
     *
     * <pre>
     * Future&#60;JobEvent&#62 future = command.send();
     * JobEvent event = future.join();
     * </pre>
     *
     * @return a future tracking state of success/failure of the command.
     */
    ZeebeFuture<T> send();
}
